#!/usr/bin/env node
import { Command } from 'commander';
import { registeralarmseventsCommand } from './commands/alarms---events';
import { registerauthenticationusermanagementsCommand } from './commands/authentication---user-managements';
import { registerdeckdashboardmanagementsCommand } from './commands/deck---dashboard-managements';
import { registerdnp3bacnetsCommand } from './commands/dnp3---ba-cnets';
import { registeredgemqttsystemtemplatesCommand } from './commands/edge--mqtt---system-templates';
import { registergeneraldatasourcesCommand } from './commands/general-data-sources';
import { registeriec104sCommand } from './commands/iec-104s';
import { registermodbusCommand } from './commands/modbus';
import { registernodeconfigurationsCommand } from './commands/node-configurations';
import { registeropcuaopcdasCommand } from './commands/opc-ua---opc-das';
import { registerorganizationcataloguesCommand } from './commands/organization---catalogues';
import { registers7sCommand } from './commands/s7s';
import { registertagstopicsdatapointsCommand } from './commands/tags--topics---data-points';

const program = new Command();

program
  .name('tdsplcategorized')
  .description('AXI-compliant CLI generated by ASC')
  .version('1.0.0');

registeralarmseventsCommand(program);
registerauthenticationusermanagementsCommand(program);
registerdeckdashboardmanagementsCommand(program);
registerdnp3bacnetsCommand(program);
registeredgemqttsystemtemplatesCommand(program);
registergeneraldatasourcesCommand(program);
registeriec104sCommand(program);
registermodbusCommand(program);
registernodeconfigurationsCommand(program);
registeropcuaopcdasCommand(program);
registerorganizationcataloguesCommand(program);
registers7sCommand(program);
registertagstopicsdatapointsCommand(program);

program.parse(process.argv);