#!/usr/bin/env node
import * as dotenv from 'dotenv';
dotenv.config();

import { Command } from 'commander';
import { registeralarmseventsCommand } from './commands/alarms---events';
import { registerauthenticationusermanagementsCommand } from './commands/authentication---user-managements';
import { registerdeckdashboardmanagementsCommand } from './commands/deck---dashboard-managements';

const program = new Command();

program
  .name('tdsplcategorized')
  .description('AXI-compliant CLI generated by ASC')
  .version('1.0.0');

registeralarmseventsCommand(program);
registerauthenticationusermanagementsCommand(program);
registerdeckdashboardmanagementsCommand(program);

program.parse(process.argv);